name: Preflight

on:
  workflow_call:
    secrets:
      token:
        description: "The Broker token"
        required: true
permissions: {}

jobs:
  check-jwt:
    name: Check broker token
    uses: ./.github/workflows/check-token.yaml
    secrets:
      token: ${{ secrets.token }}
  check-build-artifact:
    name: Check build artifact
    uses: ./.github/workflows/check-build-artifact.yaml
    if: github.workflow == 'Deploy pipeline - java-maven-pipeline-example'
