name: Preflight

on:
  workflow_call:
    secrets:
      token:
        description: "The Broker token"
        required: true
permissions: {}

jobs:
  check-jwt:
    name: Check broker token
    uses: ./.github/workflows/check-token.yaml
    secrets:
      token: ${{ secrets.token }}
  echo-vars:
    name: echo variables
    runs-on: ubuntu-latest
    steps:
      - name: Echo Variables
        run: |
          echo "Workflow: ${{ github.workflow }}"
          echo "Action: ${{ github.action }}"
