name: Post-Deploy Always Success

on:
  workflow_call:
permissions: {}

jobs:
  return-success-example:
    name: Sample Post-Deploy Always Success
    steps:
      - run: echo "This should succeed."
